language: android
sudo: required
jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - ANDROID_API=25
    - EMULATOR_API=25
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_BUILD_TOOLS=27.0.3
    - ADB_INSTALL_TIMEOUT=5 # minutes
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API_LEVEL
    - extra-android-m2repository # for design library
    - extra-google-m2repository
    - extra-google-google_play_services
    - addon-google_apis-google-19 # google play services
    - $ANDROID_TARGET
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
  licenses:
    - 'android-sdk-license-.+'
    - '.+'

before_script:
  - chmod +x gradlew      #Grand permissions
  - android list targets
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api
  - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator
  -
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - cp ./android-sdk-license/* "$ANDROID_HOME/licenses/"
  - chmod +x gradlew
  - pip install --user codecov
  - ./gradlew dependencies || true

after_success:
  - codecov

script:
  - echo "Building app"
  - android-wait-for-emulator
  - adb devices   #Display list of devices
  - adb shell input keyevent 82 &
  - ./gradlew clean assemble jacocoTestReport connectedCheck
